### ISSUE TITLE
setting getters fails in strict mode

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/choo-devtools#20]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Getter_only?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default
which is a problem when compiling using Babel

**Comment by YerkoPalma** [comment]
These are the getter only properties I found

- choo.help
- choo.log
- choo.history
- choo.storage
- choo.debug

But I'm not seeing any place where we are setting them.

**Comment by yoshuawuyts** [comment]
odd, I'm no longer getting this error. Closing for now I guess
