### ISSUE TITLE
Optionally aggregating events?

### ISSUE THREAD

**Issue by chinedufn** [choojs/choo-devtools#27]
## The Problem

I'm working on a WebGL game and I'm porting the HTML interface (health bars.. inventory.. things of that nature) from `virtual-dom` over to `choo`.

While doing this I tried out `choo-devtools` and ran into an issue that makes it unusable for me.

I emit events every ~600ms when the server sends down an update about the world state.

I also emit events anytime the mouse moves.

This led to my console getting blasted with noise, which has led me to turn off choo-devtools.

## How I pass events

I have one main event that I listen on called `EVENT_ROUTER` and then depending on whether `data.r` or `data.s` is set I'll route the event to the appropriate handler. I say this to illustrate that a solution that only looked at the event name wouldn't work for me. It would likely need to be able to look at the emitted data.

## Example

![image](https://user-images.githubusercontent.com/2099811/37033010-5e5ee6a8-2112-11e8-978c-82fb5d449835.png)

## One potential solution

The first potential solution that comes to mind comes with some additional API complexity so no worries at all if you believe that it isn't worth it (or if a better solution comes to mind)! I don't mind forking an maintaining my own personal hacky version in order to keep mainline simple.

- choo-devtools accepts options

```js
var devtools = require('choo-devtools')
var choo = require('choo')
var app  = choo()
// A quick and dirty example of aggregating events that came in in a row with data with the property `r`.
// You could also optionally aggregate on event name
// You could also optionally blacklist an event from being logged.
// Yeah yeah.. complexity...
app.use(devtools({aggregate: {dataProp: 'r'})
```

So 600ms go by and an event is logged to the console by choo devtools. But another 600ms goes by and the same event happens and nothing is logged. choo-devtools just adds them to an object or array or something.

Eventually a different event happens and choo-devtools logs an object or array or something with info about all of the aggregated events as well as this new event. This would be collapsed in people's consoles so it wouldn't be a data flood like it is now.

## Potential solution 2

If I could just completely turn off logging to the console and manually call `choo.log` I'd be happier then I am now for sure! I really just want to clean up my console at a minimum.

---

Alright through this together quickly to see if its even something that `choo-devtools` would consider. Happy to go into more detail / discuss more if so! And even if not thanks for reading!

**Comment by yoshuawuyts** [comment]
Hmm, I'm thinking perhaps an optional `filter` function might solve this. It's hard to find a one-size-fits all solution for this; but if people are able to extend it to their use case we might be able to solve it.

Was thinking something like this:
```js
var app = choo()
app.use(require('choo-devtools')({ filter: filter })
app.mount('body')

function filter (eventName, data) {
  if (eventName === 'EVENT_ROUTER') return false
  return true
}
```

This should also allow you to get more creative and extend it to have aggregate events - e.g. by recording the data in the filter, and re-emitting an event after a timeout / debounce. Do you think that'd work for you?

**Comment by chinedufn** [comment]
Ah - Love it!

One thing that this would not allow me to do is collect a bunch of logs and log them all at once.

i.e. if 500 logs with the same `data.foo` property come in in a row I want nothing logged to the console until the last one comes and then it logs an array of all of those events.. or something..

quick rough illustration...:

```js
app.use(require('choo-devtools')({filter: filter})

var batchedEvents = []
var lastEvent = null
function filter (eventName, data) {
  batchedEvents.push({name: eventName, data: data})
  if (eventName === 'REPETITIVE_EVENT' && lastEvent === eventName) return false

  lastEvent = eventName
  var clone = batchedEvents.slice(0)
  batchedEvents = []
  return clone
}
```

And if choo-devtools receives an array of events it prints the entire array. Developer can then expand that array in their console if they want.

---

One downside in the above is that once you return a batch the last item in the batch would actually be a different event.... so maybe your filter could return a data structure that told choo-devtools: "log all of these events together, but log this event alone".

i.e.

```js
function filter (eventName, data) {
  // ...
  return [
    [.. a bunch of events to print out together in one array...],
    .. one event to print out by itself ..
  ]
}
```

But regardless... just your example alone would solve the bulk of my problems. Being able to print a batch of logs would just be icing on the cake.

Thoughts?

**Comment by yoshuawuyts** [comment]
@chinedufn I think that's a very reasonable approach! :+1:

**Comment by chinedufn** [comment]
Cool! I'm pretty free next week so I'm happy to 

1. Take a stab at this and PR

2. Clean up the PR based on your feedback

Cheers!

**Comment by yoshuawuyts** [comment]
@chinedufn woooot! :grin:
