### ISSUE TITLE
Non-transpiled ES2015+ code prevents usage in IE

### ISSUE THREAD

**Issue by Alamantus** [choojs/choo-devtools#31]
This may be a non-issue, since I don't know of anyone who would use IE for development, but I think it bears mentioning since I discovered the problem when I was trying to test IE before building production code:

When using choo-devtools as a dependency with a code bundler (I'm using [Parcel](parceljs.org)), the bundler does not run Babel on dependencies because they are supposed to be(?) delivered in a compatible form using standard (<ES2015) code.

If you can submit pre-transpiled code to NPM instead of the source, then I believe this would solve the problem.

**Comment by goto-bus-stop** [comment]
Debugging in IE seems like a very valid use case. Thanks for bringing it up! It looks like we're mostly using template strings in some places; it would be easiest to just replace those with 'normal' strings and + concats.

**Comment by Alamantus** [comment]
That seems simple enough. I noticed another part, in the export, I think, that's using an arrow function. That and the template strings are all I noticed from the IE console before I created this issue.

Thanks!

**Comment by Alamantus** [comment]
Fixed in PR #32 :tada:
