### ISSUE TITLE
allow state copying

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/choo-devtools#4]
expose https://github.com/jekrb/state-copy as `choo.copy()`. Also allow selecting sub values with the dot notation e.g. `choo.copy('form.values')`

**Comment by yoshuawuyts** [comment]
e.g. use https://github.com/hughsk/plucker

**Comment by yoshuawuyts** [comment]
cc/ @jekrb would you be interested in PRing this? :sparkles:

**Comment by jakeburden** [comment]
@yoshuawuyts yes I'd be delighted 😄

**Comment by yoshuawuyts** [comment]
woot! 🎉

**Comment by yoshuawuyts** [comment]
yay!
