### ISSUE TITLE
'DOMContentLoaded' isn't being emitted 

### ISSUE THREAD

**Issue by jakeburden** [choojs/choo-devtools#7]
I'll take a look at this more deeply this evening after work, just setting a reminder for myself.
After merging #6 ( thanks again @auggod for fixing my syntax error!) I did a quick test and it seems that this event isn't firing for me

```js
emitter.on('DOMContentLoaded', function () {
```

**Comment by yoshuawuyts** [comment]
That's odd - it should always fire outside Node

**Comment by jakeburden** [comment]
oops just tried choo 6.0.0-3 and this works fine there 😸 
closing ☮️
