### ISSUE TITLE
capture nanocomponent boot performance

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/choo-devtools#8]
Found this cool screenshot from react-perf inside a table, ([source](https://github.com/reddit/reddit-mobile/issues/247)). To audit boot performance, it'd be super cool if we could make this part of devtools!

![screenshot from react-perf](https://cloud.githubusercontent.com/assets/39191/8503413/d687dc26-2173-11e5-8311-3991d4a8bb3f.png)

**Comment by yoshuawuyts** [comment]
Oh, lol - apparently this is Google sheets. But I bet we could recreate it wish some ASCII art!

**Comment by marlun** [comment]
What about https://developer.mozilla.org/en-US/docs/Web/API/Console/table ?

**Comment by yoshuawuyts** [comment]
Yeah, we're using that for choo.log in the console too right now. Would be
so cool if we could recreate spark lines in it!

**Comment by yoshuawuyts** [comment]
Ohh, so I got sparklines working the other day:

<img width="707" alt="screen shot 2017-09-10 at 18 48 22" src="https://user-images.githubusercontent.com/2467194/30321074-0c1169f2-97b5-11e7-9c38-a8f0f4129ab8.png">


But we can take our viz even further with http://aftertheflood.co/projects/atf-spark;
text-only spark charts charts inside the console would be sickkkk.

**Comment by yoshuawuyts** [comment]
Also this is too sick https://www.scribbletone.com/typefaces/ff-chartwell - not open source tho, but maybs we can figure something out :D

**Comment by bcomnes** [comment]
Sick

**Comment by yoshuawuyts** [comment]
Sweet bb devtools https://bugzilla.mozilla.org/show_bug.cgi?id=1399897 - talked to folks on twitter and this might just become real good on Firefox! :D

**Comment by yoshuawuyts** [comment]
Updates!

- low res spark lines - https://twitter.com/TatumCreative/status/908366218305863682
- custom font support in devtools https://bugzilla.mozilla.org/show_bug.cgi?id=1399902
- in the issue ^ there's an issue for better `console.table()` support. Moz is killin it

**Comment by yoshuawuyts** [comment]
I think now that we have this render timing here, we can do it:
- https://github.com/choojs/nanocomponent/blob/master/index.js#L42
